# SPDX-License-Identifier: AGPL-3.0-or-later
---
# tasks file for OpenBao installation from binary tarball
# ------------------------------------------------------------------------
# Install OpenBao from a released binary tarball when the role is
# configured for binary-based deployment. This file checks the currently
# installed version, ensures the required package dependencies are
# present, downloads and verifies the archive, extracts it into the
# runtime directory, creates the systemd unit, and enables the OpenBao
# service.

- name: Check currently installed OpenBao version
  ansible.builtin.command:
    argv:
      - "{{ openbao_configuration_runtime_path ~ '/bao' }}"
      - "-version"
  ignore_errors: true
  changed_when: false
  register: openbao_task_result_version_check

- name: Determine whether OpenBao needs installation
  ansible.builtin.set_fact:
    openbao_installed_version: >-
      {{ openbao_task_result_version_check.stdout
      | regex_search('v(\d+\.\d+\.\d+)') }}

- name: Determine whether OpenBao needs installation
  ansible.builtin.set_fact:
    openbao_needs_install: >-
      {{
        openbao_task_result_version_check.rc != 0
        or openbao_installed_version != 'v' ~ openbao_version
      }}
  when: openbao_task_result_version_check is defined

- name: Create OpenBao directory
  when: openbao_needs_install
  ansible.builtin.file:
    path: "{{ openbao_configuration_runtime_path }}"
    state: directory
    mode: "0750"
    owner: "{{ openbao_user_name }}"
    group: "{{ openbao_user_group_name }}"

- name: Install OpenBao from URL
  when: openbao_needs_install
  become: true
  become_user: "{{ openbao_user_name }}"
  block:
    - name: Create temporary staging directory
      ansible.builtin.tempfile:
        state: directory
      register: openbao_task_result_staging_dir
    - name: Download OpenBao package
      ansible.builtin.get_url:
        url: "{{ openbao_binary_package_download_url }}"
        dest: "{{ openbao_task_result_staging_dir.path }}"
        mode: "0750"

    - name: GPG key verification
      when:
        - openbao_binary_package_gpg_key_verification
        - openbao_needs_install
      block:
        - name: Download OpenBao package GPG key
          ansible.builtin.get_url:
            url: "{{ openbao_binary_package_download_gpg_key_url }}"
            dest: >-
              {{ openbao_task_result_staging_dir.path ~
              '/' ~ openbao_binary_package_download_gpg_key_url | basename }}
            mode: "0750"
        - name: Copy OpenBao public GPG key to remote host
          ansible.builtin.copy:
            src: "{{ openbao_binary_package_gpg_public_key_file }}"
            dest: >-
              {{ openbao_task_result_staging_dir.path ~
              '/' ~ openbao_binary_package_gpg_public_key_file | basename }}
            mode: "0750"
        - name: Import OpenBao public GPG key
          ansible.builtin.command:
            argv:
              - "gpg"
              - "--no-tty"
              - "--logger-fd"
              - "1"
              - "--homedir"
              - "{{ openbao_task_result_staging_dir.path }}"
              - "--no-autostart"
              - "--import"
              - >-
                  {{ openbao_task_result_staging_dir.path ~
                  '/' ~ openbao_binary_package_gpg_public_key_file | basename }}
          register: openbao_task_result_public_gpg_key_import
          failed_when: openbao_task_result_public_gpg_key_import.rc != 0
          changed_when: false
        - name: Verify OpenBao package GPG key
          ansible.builtin.command:
            argv:
              - "gpg"
              - "--no-tty"
              - "--logger-fd"
              - "1"
              - "--homedir"
              - "{{ openbao_task_result_staging_dir.path }}"
              - "--no-autostart"
              - "--verify"
              - >-
                {{ openbao_task_result_staging_dir.path ~
                '/' ~ openbao_binary_package_download_gpg_key_url | basename }}
              - >-
                {{ openbao_task_result_staging_dir.path ~
                '/' ~ openbao_binary_package_download_url | basename }}
          register: openbao_task_result_gpg_check
          failed_when: openbao_task_result_gpg_check.rc != 0
          changed_when: false

    - name: Extract OpenBao package
      ansible.builtin.unarchive:
        src: >-
          {{ openbao_task_result_staging_dir.path ~
          '/' ~ openbao_binary_package_download_url | basename }}
        dest: "{{ openbao_configuration_runtime_path }}"
        remote_src: true
        mode: "0755"
      notify: restart_cluster
  always:
    - name: Clean up temporary staging directory
      when: openbao_task_result_staging_dir.path is defined
      ansible.builtin.file:
        path: "{{ openbao_task_result_staging_dir.path }}"
        state: absent

- name: Add systemd service file for OpenBao
  become: true
  become_user: "{{ openbao_user_name }}"
  block:
    - name: Create systemd directory for OpenBao
      ansible.builtin.file:
        path: "{{ openbao_configuration_data_systemd_path }}"
        state: directory
        mode: "0755"
    - name: Add systemd configuration file for OpenBao
      ansible.builtin.template:
        src: "openbao.service.j2"
        dest: >-
          {{ openbao_configuration_data_systemd_path ~
          '/' ~ openbao_configuration_data_systemd_unit_name }}
        mode: "0644"
      notify: restart_cluster

- name: Enable OpenBao systemd service
  become: true
  ansible.builtin.systemd:
    name: >-
      {{ openbao_configuration_data_systemd_path ~
      '/' ~ openbao_configuration_data_systemd_unit_name }}
    enabled: true
    daemon_reload: true
