# SPDX-License-Identifier: AGPL-3.0-or-later
---
# tasks file for OpenBao pre-installation setup
# ------------------------------------------------------------------------
# Collects information about installed packages and creates the
# configured system user and home directory when local user provisioning
# is enabled.

- name: "Collect installed packages information"
  ansible.builtin.package_facts:
    manager: "auto"

- name: Create OpenBao user
  when: openbao_user_creation
  become: true
  ansible.builtin.user:
    comment: "Local user for OpenBao"
    name: "{{ openbao_user_name }}"
    home: "{{ openbao_user_home }}"
    create_home: "{{ openbao_user_home_creation }}"
    force: true
