---
dependency:
  name: galaxy
  options: {}
driver:
  name: docker
platforms:
  - name: instance
    image: alpine:3.18
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  directory: tests
scenario:
  name: default
  test_sequence:
    - lint
    - dependency
    - create
    - prepare
    - converge
    - verify
    - destroy
