---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Run Testinfra tests
      ansible.builtin.command: pytest -q
      args:
        chdir: molecule/default/tests
      register: openbao_pytest_result
      failed_when: openbao_pytest_result.rc != 0
      changed_when: false
